# Generated by Django 3.2.7 on 2021-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_local',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Poster'),
        ),
    ]
