# Generated by Django 3.2.1 on 2021-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.Tags'),
        ),
    ]
