# Generated by Django 3.2.1 on 2021-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211027_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_local',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Poster'),
        ),
    ]
